### ISSUE TITLE
Could you tell me what is the purpose of this project

### ISSUE THREAD

**Issue by xuanmumy** [ProjectMile/Mile.Project.Windows#4]
I am jump from lvgl to this. 
I am not a windows developer. So rarely I use vs studio. 
My problem is the lvgl simulator contains lvgl 9.0 code. I want to switch to 3.8.x , fast switch from version to version would be great to compare features. when I replace lvgl 3.8.4 eg. it will generate a lot of errors missing files. it is annoying to check file by file. And seems there is no add external folder option in vs studio.
will this mile.project.windows tool help to do so?    can you give me some suggestion?

**Comment by MouriNaruto** [comment]
It simplifies the Visual Studio project configuration and helps people to write a simple configuration for projects.

For LVGL simulator 8.x branch, it uses the old customized version of this project. In 9.x branch, I think we should use the mainline one because it contains more fixes and features.

Kenji Mouri

**Comment by xuanmumy** [comment]
thanks
